export const ADD_TODO = "ADD_TODO";
export const CLEAR_COMPLETED = "CLEAR_COMPLETED";
export const TOGGLE_MINIMIZED = "TOGGLE_MINIMIZED";
export const TOGGLE_COMPLETED = "TOGGLE_COMPLETED";
export const HANDLE_INPUT_CHANGES = "HANDLE_INPUT_CHANGES";